ci:
  skip: [hatch-test, taplo, tox]
repos:
  - repo: https://github.com/ComPWA/mirrors-taplo
    rev: "v0.8.1"
    hooks:
      - id: taplo
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
      - id: reorder-python-imports
        args: [--py37-plus, --add-import, "from __future__ import annotations"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.0
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.3
    hooks:
      - id: actionlint

  # - repo: https://github.com/python-jsonschema/check-jsonschema
  #   rev: 0.28.0
  #   hooks:
  #     - id: check-github-workflows
  #       args: ["--verbose"]
  - repo: local
    hooks:
      - id: tox
        name: tox
        entry: tox run-parallel
        language: python
        additional_dependencies: ["tox"]
        pass_filenames: false
        always_run: true
        types: [python]
      - id: hatch-test
        name: hatch-test
        entry: env HATCH_ENV_TYPE_VIRTUAL_PATH= hatch test --parallel --all
        language: python
        additional_dependencies: [hatch>=1.12.0]
        pass_filenames: false
        always_run: true
