name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main:
    uses: ./.github/workflows/common-python.yml
    secrets:
      PYPI_API_TOKEN: 'NONE'
    with:
      pypa-name: pypa-name-holder
      zipapp-entrypoint: dev
    permissions:
      contents: write
      id-token: write
