name: main

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  main:
    if: true
    uses: ./.github/workflows/common-python.yml
    secrets:
      PYPI_API_TOKEN: 'NONE'
    with:
      pypa-name: gh-workflows
      zipapp-entrypoint: gh-workflows
      enable-pypi: false
    permissions:
      contents: write
      id-token: write
